import React, {useEffect, useState} from 'react';
import {request,API} from '../auth/api';

type DashboardProps={session:any; onClose:()=>void};
type Data={summary:any;timeseries:any[];breakdowns:any};
export default function AdminDashboard({session,onClose}:DashboardProps){
 const [days,setDays]=useState(30); const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{setData(await request(`/admin-analytics/dashboard/?days=${days}`,{},session.access))}catch(e:any){setError(e.message||'Não foi possível carregar o painel.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[days]);
 if(!session?.user?.is_staff)return <div className="modal"><div className="modalBox"><button className="close" onClick={onClose}>×</button><h2>Acesso restrito</h2><p>Esta área está disponível apenas para administradores.</p></div></div>;
 const s=data?.summary; const cards=s?[['Utilizadores',s.users],['Novos utilizadores',s.new_users],['Anúncios publicados',s.published_listings],['Pedidos',s.orders],['Vendas',`${Number(s.gross_sales||0).toLocaleString('pt-AO')} AOA`],['Ticket médio',`${Number(s.average_order_value||0).toLocaleString('pt-AO')} AOA`],['Consultorias',s.consultation_requests],['Denúncias abertas',s.open_reports]]:[];
 const max=Math.max(1,...(data?.timeseries||[]).map(x=>Number(x.orders||0)));
 return <div className="modal adminModal"><div className="modalBox adminBox"><button className="close" onClick={onClose}>×</button><div className="adminHeader"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h2>Painel AgroNova</h2><p>Monitorização operacional e financeira da plataforma.</p></div><div className="adminActions"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={365}>365 dias</option></select><button className="ghost" onClick={load}>Atualizar</button><a className="ghost" href={`${API}/admin-analytics/export.csv?days=${days}`} target="_blank" rel="noreferrer">CSV</a></div></div>{loading?<div className="notice">A carregar métricas...</div>:error?<div className="notice error">{error}</div>:<><div className="metricGrid">{cards.map(([label,value])=><div className="metricCard" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="adminGrid"><section className="adminPanel"><h3>Pedidos por dia</h3><div className="bars">{(data?.timeseries||[]).slice(-14).map(x=><div className="barCol" key={x.date}><div className="bar" style={{height:`${Math.max(5,Number(x.orders||0)/max*120)}px`}} title={`${x.orders} pedidos`}/><small>{x.date.slice(5)}</small></div>)}</div></section><section className="adminPanel"><h3>Distribuição</h3><List title="Utilizadores por perfil" rows={data?.breakdowns?.users_by_role||[]} label="role"/><List title="Pedidos por estado" rows={data?.breakdowns?.orders_by_status||[]} label="status"/></section></div><div className="adminGrid"><section className="adminPanel"><h3>Anúncios por estado</h3><List rows={data?.breakdowns?.listings_by_status||[]} label="status"/></section><section className="adminPanel"><h3>Consultorias por estado</h3><List rows={data?.breakdowns?.consultations_by_status||[]} label="status"/></section></div></>}</div></div>
}
function List({title,rows,label}:{title?:string;rows:any[];label:string}){return <div className="statList">{title&&<h4>{title}</h4>}{rows.map((r,i)=><div className="statRow" key={i}><span>{r[label]||'—'}</span><b>{r.count}</b></div>)}</div>}
