from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[('accounts','0001_initial'),('catalog','0001_initial')]
    operations=[
      migrations.CreateModel(name='Listing',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('description',models.TextField(blank=True)),('price',models.DecimalField(decimal_places=2,max_digits=14)),('currency',models.CharField(default='AOA',max_length=3)),('unit',models.CharField(default='unidade',max_length=40)),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('status',models.CharField(choices=[('DRAFT','Rascunho'),('PUBLISHED','Publicado'),('PAUSED','Pausado'),('SOLD_OUT','Esgotado'),('ARCHIVED','Arquivado')],default='DRAFT',max_length=20)),('location_text',models.CharField(blank=True,max_length=255)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='listings',to='catalog.category')),('seller',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='listings',to='accounts.user'))],options={'ordering':['-created_at'] }),
      migrations.CreateModel(name='ListingImage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='listings/')),('sort_order',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('listing',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='listings.listing'))],options={'ordering':['sort_order','id']}),
      migrations.CreateModel(name='Favorite',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('listing',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='favorited_by',to='listings.listing')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='favorites',to='accounts.user'))],options={'constraints':[models.UniqueConstraint(fields=('user','listing'),name='unique_user_listing_favorite')]}),
    ]
