import React,{useEffect,useState} from 'react';
import {SafeAreaView,Text,View,StyleSheet,TextInput,Pressable,FlatList,ActivityIndicator,Modal,Alert} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Notifications from 'expo-notifications';
import {registerForPushNotifications,notificationSocket} from './notifications';
const API=(process.env.EXPO_PUBLIC_API_URL||'http://localhost:8000/api/v1').replace(/\/$/,'');
type Listing={id:string;title:string;price:string|number;currency?:string;unit?:string;location?:string;category?:string}; type Session={access:string;refresh:string;user:any};
async function req(path:string,opts:any={},token?:string){const h:any={'Content-Type':'application/json',...(opts.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(`${API}${path}`,{...opts,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||b.error?.message||`Erro ${r.status}`);return b}
export default function App(){const [q,setQ]=useState('');const [items,setItems]=useState<Listing[]>([]);const [busy,setBusy]=useState(true);const [session,setSession]=useState<Session|null>(null);const [auth,setAuth]=useState(false);const [registerMode,setRegisterMode]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [role,setRole]=useState('FARMER');const [unread,setUnread]=useState(0);
 useEffect(()=>{AsyncStorage.getItem('agronova_session').then(x=>{if(x)setSession(JSON.parse(x))});fetch(`${API}/listings/`).then(r=>r.json()).then(x=>setItems(x.data??x.results??x??[])).catch(()=>setItems([])).finally(()=>setBusy(false)); const sub=Notifications.addNotificationReceivedListener(()=>setUnread(v=>v+1)); return()=>sub.remove()},[]);
 useEffect(()=>{if(!session)return; registerForPushNotifications(session.access).catch(()=>{}); req('/notifications/unread_count/',{},session.access).then(x=>setUnread(x.count||0)).catch(()=>{}); const ws=notificationSocket(session.access,e=>{if(e.type==='notification.created'){setUnread(v=>v+1); Alert.alert(e.notification.title,e.notification.message)}}); return()=>ws.close()},[session]);
 const filtered=items.filter(x=>`${x.title} ${x.category} ${x.location}`.toLowerCase().includes(q.toLowerCase()));
 async function submit(){try{const b=registerMode?await req('/auth/register/',{method:'POST',body:JSON.stringify({email,password,phone:null,full_name:name,role})}):await req('/auth/token/',{method:'POST',body:JSON.stringify({email,password})});const s:any=registerMode?{...b.data}:{access:b.access,refresh:b.refresh};if(!registerMode)s.user=await req('/auth/me/',{},s.access);else s.user=b.data.user;await AsyncStorage.setItem('agronova_session',JSON.stringify(s));setSession(s);setAuth(false);Alert.alert('AgroNova',registerMode?'Conta criada com sucesso.':'Sessão iniciada.')}catch(e:any){Alert.alert('Não foi possível entrar',e.message)}} async function logout(){await AsyncStorage.removeItem('agronova_session');setSession(null);setUnread(0)}
 return <SafeAreaView style={s.safe}><FlatList data={filtered} keyExtractor={x=>x.id} contentContainerStyle={s.container} ListHeaderComponent={<><View style={s.top}><Text style={s.brand}>AgroNova</Text><View style={{flexDirection:'row',gap:10}}>{session&&<Pressable onPress={()=>setUnread(0)} style={s.bell}><Text>🔔 {unread}</Text></Pressable>}<Pressable style={s.login} onPress={()=>session?logout():setAuth(true)}><Text style={s.loginText}>{session?'Sair':'Entrar'}</Text></Pressable></View></View><Text style={s.eyebrow}>MARKETPLACE AGRÍCOLA</Text><Text style={s.title}>Do campo para o mercado.</Text><Text style={s.body}>Encontre produtos, produtores e oportunidades perto de si.</Text><TextInput value={q} onChangeText={setQ} placeholder="Pesquisar produtos..." style={s.search}/>{busy&&<ActivityIndicator/>}<Text style={s.heading}>Produtos em destaque</Text></>} renderItem={({item})=><Pressable style={s.card}><View style={s.photo}><Text style={{fontSize:40}}>🌾</Text></View><View style={s.cardBody}><Text style={s.category}>{item.category||'Agricultura'}</Text><Text style={s.name}>{item.title}</Text><Text style={s.meta}>{item.location||'Angola'} · {item.unit||'un.'}</Text><Text style={s.price}>{Number(item.price).toLocaleString('pt-AO')} {item.currency||'AOA'} / {item.unit||'un.'}</Text></View></Pressable>}/>} />
 <Modal visible={auth} transparent animationType="fade"><View style={s.overlay}><View style={s.modal}><Pressable onPress={()=>setAuth(false)}><Text style={s.close}>×</Text></Pressable><Text style={s.modalTitle}>{registerMode?'Criar conta':'Entrar'}</Text>{registerMode&&<TextInput placeholder="Nome completo" value={name} onChangeText={setName} style={s.input}/>}<TextInput placeholder="E-mail" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={s.input}/><TextInput placeholder="Senha (mín. 8)" secureTextEntry value={password} onChangeText={setPassword} style={s.input}/>{registerMode&&<TextInput placeholder="Perfil: FARMER / BUYER / COMPANY" value={role} onChangeText={setRole} style={s.input}/>}<Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>{registerMode?'Criar conta':'Entrar'}</Text></Pressable><Pressable onPress={()=>setRegisterMode(!registerMode)}><Text style={s.switch}>{registerMode?'Já tenho conta':'Criar nova conta'}</Text></Pressable></View></View></Modal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7f2'},container:{padding:22},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:28,fontWeight:'900',color:'#172019'},login:{backgroundColor:'#172019',paddingHorizontal:16,paddingVertical:9,borderRadius:10},loginText:{color:'#fff',fontWeight:'800'},bell:{backgroundColor:'#fff',paddingHorizontal:10,paddingVertical:8,borderRadius:10},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:2,color:'#58705b',marginTop:28},title:{fontSize:42,fontWeight:'900',letterSpacing:-1.5,color:'#172019',marginTop:10},body:{fontSize:17,lineHeight:26,color:'#697269',marginTop:12},search:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dfe5dd',borderRadius:12,padding:15,marginTop:22},heading:{fontSize:25,fontWeight:'800',marginTop:32,marginBottom:14},card:{backgroundColor:'#fff',borderRadius:16,overflow:'hidden',marginBottom:16,borderWidth:1,borderColor:'#e1e7df'},photo:{height:150,backgroundColor:'#dfe9d8',alignItems:'center',justifyContent:'center'},cardBody:{padding:18},category:{fontSize:10,fontWeight:'800',letterSpacing:1.4,color:'#58705b'},name:{fontSize:22,fontWeight:'800',marginTop:7},meta:{fontSize:14,color:'#737c73',marginTop:7},price:{fontSize:16,fontWeight:'800',marginTop:12,color:'#172019'},overlay:{flex:1,backgroundColor:'#17201988',justifyContent:'center',padding:20},modal:{backgroundColor:'#fff',borderRadius:22,padding:24},close:{fontSize:28,textAlign:'right'},modalTitle:{fontSize:30,fontWeight:'900',marginBottom:15},input:{borderWidth:1,borderColor:'#dfe5dd',borderRadius:10,padding:13,marginBottom:12},primary:{backgroundColor:'#172019',borderRadius:10,padding:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},switch:{textAlign:'center',marginTop:15,color:'#58705b',fontWeight:'700'}});
