# Generated for AgroNova Phase 3; run makemigrations in a Django environment to regenerate.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion, uuid
class Migration(migrations.Migration):
    initial=True
    dependencies=[('listings','0001_initial'),('accounts','0001_initial')]
    operations=[
      migrations.CreateModel(name='Order',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('status',models.CharField(choices=[('PENDING','Pendente'),('ACCEPTED','Aceite'),('REJECTED','Rejeitado'),('AWAITING_PAYMENT','A aguardar pagamento'),('PAID','Pago'),('PROCESSING','Em processamento'),('READY_FOR_DELIVERY','Pronto para entrega'),('IN_TRANSIT','Em trânsito'),('DELIVERED','Entregue'),('COMPLETED','Concluído'),('CANCELLED','Cancelado'),('DISPUTED','Em disputa'),('REFUNDED','Reembolsado')],default='PENDING',max_length=30)),('subtotal',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('fees',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('currency',models.CharField(default='AOA',max_length=3)),('delivery_address',models.CharField(blank=True,max_length=500)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('buyer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='purchase_orders',to=settings.AUTH_USER_MODEL)),('seller',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='sales_orders',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('unit_price',models.DecimalField(decimal_places=2,max_digits=14)),('unit',models.CharField(max_length=40)),('subtotal',models.DecimalField(decimal_places=2,max_digits=16)),('listing',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='order_items',to='listings.listing')),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='orders.order'))]),
      migrations.CreateModel(name='OrderStatusHistory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('from_status',models.CharField(blank=True,max_length=30)),('to_status',models.CharField(max_length=30)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='order_status_changes',to=settings.AUTH_USER_MODEL)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='status_history',to='orders.order'))]),
      migrations.CreateModel(name='Payment',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('provider',models.CharField(max_length=80)),('provider_ref',models.CharField(blank=True,max_length=180)),('status',models.CharField(choices=[('PENDING','Pendente'),('PAID','Pago'),('FAILED','Falhou'),('REFUNDED','Reembolsado')],default='PENDING',max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=16)),('currency',models.CharField(max_length=3)),('idempotency_key',models.CharField(max_length=180,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('order',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payments',to='orders.order'))]),
      migrations.AddConstraint(model_name='orderitem',constraint=models.UniqueConstraint(fields=('order','listing'),name='unique_order_listing'))]
