from django.db import migrations, models
import django.db.models.deletion, uuid
import django.conf
from django.core.validators import MinValueValidator
from decimal import Decimal

class Migration(migrations.Migration):
    initial=True
    dependencies=[('orders','0001_initial')]
    operations=[
        migrations.CreateModel(name='Wallet',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('currency',models.CharField(default='AOA',max_length=3)),('available_balance',models.DecimalField(decimal_places=2,default=0,max_digits=18,validators=[MinValueValidator(Decimal('0'))])),('pending_balance',models.DecimalField(decimal_places=2,default=0,max_digits=18,validators=[MinValueValidator(Decimal('0'))])),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='finance_wallet',to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='LedgerEntry',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('entry_type',models.CharField(choices=[('SALE','Venda'),('COMMISSION','Comissão'),('REFUND','Reembolso'),('PAYOUT','Levantamento'),('ADJUSTMENT','Ajuste')],max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=18)),('currency',models.CharField(default='AOA',max_length=3)),('reference',models.CharField(max_length=180,unique=True)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='finance_entries',to='orders.order')),('wallet',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='ledger',to='finance.wallet'))]),
        migrations.CreateModel(name='Settlement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('gross_amount',models.DecimalField(decimal_places=2,max_digits=18)),('commission_amount',models.DecimalField(decimal_places=2,max_digits=18)),('fees_amount',models.DecimalField(decimal_places=2,default=0,max_digits=18)),('net_amount',models.DecimalField(decimal_places=2,max_digits=18)),('currency',models.CharField(max_length=3)),('status',models.CharField(choices=[('PENDING','Pendente'),('AVAILABLE','Disponível'),('PAID','Pago'),('REVERSED','Revertido')],default='PENDING',max_length=20)),('available_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('order',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='settlement',to='orders.order')),('seller',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='settlements',to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='PayoutRequest',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('amount',models.DecimalField(decimal_places=2,max_digits=18,validators=[MinValueValidator(Decimal('0.01'))])),('currency',models.CharField(max_length=3)),('destination_type',models.CharField(max_length=40)),('destination_ref',models.CharField(max_length=180)),('status',models.CharField(choices=[('REQUESTED','Solicitado'),('PROCESSING','Processando'),('PAID','Pago'),('FAILED','Falhou'),('CANCELLED','Cancelado')],default='REQUESTED',max_length=20)),('provider_ref',models.CharField(blank=True,max_length=180)),('idempotency_key',models.CharField(max_length=180,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('wallet',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payouts',to='finance.wallet'))])]
