import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {login,register,request,API} from './auth/api';
import AdminDashboard from './admin/AdminDashboard';

function useRealtime(session:Session|null,onNotification:(n:any)=>void){React.useEffect(()=>{if(!session)return; const base=API.replace(/^http/,'ws').replace(/\/api\/v1$/,''); const ws=new WebSocket(`${base}/ws/notifications/?token=${encodeURIComponent(session.access)}`); ws.onmessage=e=>{try{const x=JSON.parse(e.data); if(x.type==='notification.created') onNotification(x.notification)}catch{}}; return()=>ws.close()},[session,onNotification])}


type Listing={id:string;title:string;description?:string;price:string|number;currency?:string;unit?:string;quantity?:string|number;status?:string;category?:any;location_text?:string;images?:any[]};
type Category={id:number;name:string;slug:string};
type Session={access:string;refresh:string;user:any};
function App(){
 const [session,setSession]=useState<Session|null>(()=>{try{return JSON.parse(localStorage.getItem('agronova_session')||'null')}catch{return null}}); const [notifications,setNotifications]=useState<any[]>([]); const [showNotifications,setShowNotifications]=useState(false);
 const handleNotification=React.useCallback((n:any)=>setNotifications(v=>[n,...v].slice(0,30)),[]); useRealtime(session,handleNotification);
 React.useEffect(()=>{if(session)request('/notifications/',{},session.access).then(x=>setNotifications(x.results??x.data??[])).catch(()=>{})},[session]);
 const [auth,setAuth]=useState<'login'|'register'|'profile'|null>(null); const [showAdmin,setShowAdmin]=useState(false); const [listings,setListings]=useState<Listing[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Listing|null>(null); const [creating,setCreating]=useState(false);
 useEffect(()=>{Promise.all([request('/listings/'),request('/catalog/categories/')]).then(([a,c])=>{setListings(a.data??a.results??a??[]);setCategories(c.data??c.results??c??[])}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 const data=listings; const filtered=useMemo(()=>data.filter(x=>`${x.title} ${x.category?.name||x.category||''} ${x.location_text||''}`.toLowerCase().includes(q.toLowerCase())),[data,q]);
 const save=(s:Session)=>{localStorage.setItem('agronova_session',JSON.stringify(s));setSession(s);setAuth(null)}; const logout=()=>{localStorage.removeItem('agronova_session');setSession(null)};
 async function createListing(payload:any){const body=await request('/listings/',{method:'POST',body:JSON.stringify(payload)},session!.access);setListings(v=>[body,...v]);setCreating(false);setSelected(body)}
 return <div><nav><div className="brand">AgroNova</div><div className="navlinks"><a>Marketplace</a><a>Pedidos</a><button onClick={()=>setShowNotifications(v=>!v)}>🔔 <span className="notificationBadge">{notifications.filter(n=>!n.read_at).length}</span></button><a>Mensagens</a>{session?.user?.is_staff&&<button onClick={()=>setShowAdmin(true)}>Admin</button>}{session?<><button className="profileBtn" onClick={()=>setAuth('profile')}>{session.user?.email}</button><button onClick={logout}>Sair</button></>:<button onClick={()=>setAuth('login')}>Entrar</button>}</div></nav>
 <main><section className="hero"><div><span className="pill">AGRO • TECNOLOGIA • MERCADO</span><h1>Do campo para o mercado, <em>sem complicação.</em></h1><p>Encontre produtos agrícolas, converse com produtores e organize pedidos numa única plataforma.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar milho, feijão, tomate..."/><button>Pesquisar</button></div></div><div className="heroCard"><div className="sun">✦</div><strong>Produção local</strong><p>Conecte produtores de Angola a compradores em todo o país.</p><div className="miniStats"><span><b>24/7</b> marketplace</span><span><b>6</b> perfis</span></div></div></section>
 <section className="section"><div className="sectionHead"><div><span className="eyebrow">OFERTAS</span><h2>Produtos em destaque</h2></div>{session&&<button className="primaryBtn" onClick={()=>setCreating(true)}>+ Publicar produto</button>}</div>{loading?<div className="notice">A carregar anúncios...</div>:<div className="grid">{filtered.length?filtered.map(x=><article className="card" key={x.id} onClick={()=>setSelected(x)}><div className="photo">🌾</div><div className="cardBody"><span className="category">{x.category?.name||x.category||'Agricultura'}</span><h3>{x.title}</h3><p>{x.location_text||'Angola'} · {x.quantity??'—'} {x.unit||'un.'}</p><strong>{Number(x.price).toLocaleString('pt-AO')} {x.currency||'AOA'} / {x.unit||'un.'}</strong></div></article>):<div className="notice">Nenhum anúncio disponível no momento.</div>}</div>}</section>
 <section className="steps"><div><span>01</span><h3>Encontre</h3><p>Pesquise produtos e produtores por categoria e localização.</p></div><div><span>02</span><h3>Negocie</h3><p>Converse diretamente e combine as condições do pedido.</p></div><div><span>03</span><h3>Compre</h3><p>Transforme a negociação em pedido e acompanhe a entrega.</p></div></section></main><footer>AgroNova · Marketplace agrícola</footer>{showNotifications&&<div className="notificationPanel"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3>Notificações</h3><button onClick={()=>session&&request("/notifications/read_all/",{method:"POST"},session.access).then(()=>setNotifications(v=>v.map(n=>({...n,read_at:new Date().toISOString()}))))}>Marcar lidas</button></div>{notifications.length?notifications.map(n=><div className="notificationItem" key={n.id}><b>{n.title}</b><div>{n.message}</div><small>{new Date(n.created_at).toLocaleString("pt-PT")}</small></div>):<p>Sem notificações.</p>}</div>}
 {selected&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="photo big">🌾</div><span className="category">{selected.category?.name||selected.category||'Agricultura'}</span><h2>{selected.title}</h2><p>{selected.description||'Produto agrícola disponível no AgroNova.'}</p><p><b>{Number(selected.price).toLocaleString('pt-AO')} {selected.currency||'AOA'}</b> / {selected.unit||'un.'}</p><p>{selected.quantity??'—'} {selected.unit||'un.'} · {selected.location_text||'Angola'}</p>{session&&<button className="primaryBtn wide" onClick={async()=>{try{await request('/cart/items/',{method:'POST',body:JSON.stringify({listing:selected.id,quantity:1})},session.access);alert('Produto adicionado ao carrinho.');}catch(e:any){alert(e.message)}}}>Adicionar ao carrinho</button>}</div></div>}
 {creating&&<CreateListing categories={categories} session={session!} onClose={()=>setCreating(false)} onCreate={createListing}/>} {auth==='login'&&<Auth mode="login" onClose={()=>setAuth(null)} onSave={save}/>} {auth==='register'&&<Auth mode="register" onClose={()=>setAuth(null)} onSave={save}/>} {auth==='profile'&&<Profile session={session!} onClose={()=>setAuth(null)}/>} {showAdmin&&<AdminDashboard session={session!} onClose={()=>setShowAdmin(false)}/>}</div>}
function Auth({mode,onClose,onSave}:{mode:'login'|'register';onClose:()=>void;onSave:(s:Session)=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [role,setRole]=useState('FARMER');const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{onSave(mode==='login'?await login(email,password):await register({email,password,phone:null,full_name:name,role}))}catch(e:any){setError(e.message)}}return <div className="modal"><div className="modalBox"><button className="close" onClick={onClose}>×</button><h2>{mode==='login'?'Entrar':'Criar conta'}</h2><form onSubmit={submit}>{mode==='register'&&<label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{mode==='register'&&<label>Perfil<select value={role} onChange={e=>setRole(e.target.value)}><option value="FARMER">Produtor</option><option value="BUYER">Comprador</option><option value="COMPANY">Empresa</option><option value="TRANSPORTER">Transportador</option><option value="CONSULTANT">Consultor</option></select></label>}<button className="primaryBtn wide" type="submit">{mode==='login'?'Entrar':'Criar conta'}</button>{error&&<p className="error">{error}</p>}</form></div></div>}
function Profile({session,onClose}:{session:Session;onClose:()=>void}){return <div className="modal"><div className="modalBox"><button className="close" onClick={onClose}>×</button><span className="eyebrow">MINHA CONTA</span><h2>{session.user?.profile?.full_name||session.user?.email}</h2><p>{session.user?.email}</p><p>Perfil: <b>{session.user?.profile?.role||'Utilizador'}</b></p><p>Conta autenticada no AgroNova.</p></div></div>}
function CreateListing({categories,session,onClose,onCreate}:{categories:Category[];session:Session;onClose:()=>void;onCreate:(p:any)=>Promise<void>}){const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [category,setCategory]=useState(categories[0]?.id?.toString()||'');const [price,setPrice]=useState('');const [unit,setUnit]=useState('kg');const [quantity,setQuantity]=useState('');const [location,setLocation]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await onCreate({title,description,category:Number(category),price,currency:'AOA',unit,quantity,status:'DRAFT',location_text:location})}catch(e:any){setError(e.message)}finally{setSaving(false)}}return <div className="modal"><div className="modalBox formModal"><button className="close" onClick={onClose}>×</button><span className="eyebrow">NOVO ANÚNCIO</span><h2>Publicar produto</h2><form onSubmit={submit}><label>Nome do produto<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Milho amarelo" required/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)} required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="formGrid"><label>Preço<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Unidade<select value={unit} onChange={e=>setUnit(e.target.value)}><option>kg</option><option>tonelada</option><option>caixa</option><option>litro</option><option>unidade</option></select></label></div><label>Quantidade<input type="number" min="0" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Localização<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Município, província"/></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Qualidade, colheita, disponibilidade..."/></label><p className="formHint">O anúncio será criado como rascunho. A publicação definitiva e o upload de fotografias serão concluídos na próxima etapa.</p><button className="primaryBtn wide" disabled={saving}>{saving?'A guardar...':'Guardar anúncio'}</button>{error&&<p className="error">{error}</p>}</form></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
